import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';

const skills=[['01','Programming','C, C++, Java and JavaScript, with a focus on problem solving and application development.','90%'],['02','Web Development','HTML, CSS and JavaScript for responsive and interactive web experiences.','86%'],['03','AWS Cloud','Working knowledge of EC2, S3, DynamoDB, CloudFront and CloudFormation.','78%'],['04','Collaboration','Communication, teamwork, leadership and problem-solving through projects and ACE activities.','88%']];
function App(){
 const [form,setForm]=useState({name:'',email:'',subject:'',message:''}); const [status,setStatus]=useState('');
 const submit=async e=>{e.preventDefault();setStatus('Sending...');try{const r=await fetch(`${import.meta.env.VITE_API_URL||''}/api/contact`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw Error(d.error);setStatus(d.message);setForm({name:'',email:'',subject:'',message:''})}catch(err){setStatus(err.message||'Unable to send message.')}};
 return <><header className="nav"><a className="brand" href="#home">AK<span>.</span></a><nav>{['about','skills','education','projects','leadership','contact'].map(x=><a key={x} href={'#'+x}>{x[0].toUpperCase()+x.slice(1)}</a>)}</nav></header><main>
 <section id="home" className="hero section"><div><p className="eyebrow">JAVA • MERN • PROBLEM SOLVING</p><h1>Building practical<br/><span>software solutions.</span></h1><p className="lead">I'm <strong>Abishay Karlapudi</strong>, a Computer Science and Engineering graduate focused on Java, problem solving, full-stack development and scalable solutions.</p><div className="actions"><a className="btn primary" href="#projects">View my work</a><a className="btn secondary" href="#contact">Let's connect ↗</a></div></div><div className="code-card"><div className="dots">● ● ● <span>Abishay.js</span></div><pre><code><b>const</b> Abishay = {'{'}{`\n  `}focus: <i>'MERN + Java'</i>,{`\n  `}mindset: <i>'Build. Learn. Improve.'</i>{`\n`}{'}'};</code></pre></div></section>
 <section id="about" className="section two-col"><div><p className="eyebrow">01 / ABOUT</p><h2>Curious by nature.<br/>Practical by approach.</h2></div><div><p>My goal is to leverage my skills in Java, problem solving and full-stack development to contribute to innovative and scalable solutions as a Digital Specialist Engineer.</p><p>I enjoy building user-focused applications, learning new technologies and working with teams to turn ideas into practical software.</p><div className="stats"><div><b>7.5</b><small>GPA / 10</small></div><div><b>2</b><small>Web projects</small></div><div><b>200+</b><small>Students reached</small></div></div></div></section>
 <section id="skills" className="section"><p className="eyebrow">02 / SKILLS</p><h2>Technical toolkit</h2><div className="skill-grid">{skills.map(s=><article key={s[0]}><span>{s[0]}</span><h3>{s[1]}</h3><p>{s[2]}</p><div className="bar"><i style={{width:s[3]}}/></div></article>)}</div></section>
 <section id="education" className="section"><p className="eyebrow">03 / EDUCATION</p><h2>Academic foundation</h2><div className="projects"><article className="project featured"><div className="project-top"><span>01</span><span>OCT 2022 — MAY 2026</span></div><h3>Sagi Ramakrishnam Raju Engineering College, Bhimavaram</h3><p>B.Tech. in Computer Science and Engineering</p><div className="tags"><span>GPA 7.5 / 10</span><span>Computer Science</span></div></article><article className="project"><div className="project-top"><span>02</span><span>OCT 2020 — MAY 2022</span></div><h3>Sri Chaitanya Junior College, Vijayawada</h3><p>M.P.C</p><div className="tags"><span>GPA 7.5 / 10</span></div></article></div></section>
 <section id="projects" className="section"><p className="eyebrow">04 / PROJECTS</p><h2>Selected work</h2><div className="projects"><article className="project featured"><div className="project-top"><span>01</span><span>WEB • TEAM PROJECT</span></div><h3>Tech Learn — Educational Web Platform</h3><p>Built a responsive educational website to help students grasp web development basics. Developed interactive tutorials and modular layouts with clean, beginner-friendly UI/UX while collaborating with a team of 4.</p><div className="tags"><span>HTML</span><span>CSS</span><span>JavaScript</span><span>GitHub</span></div></article><article className="project"><div className="project-top"><span>02</span><span>WEB • FULL PROJECT</span></div><h3>Student Details Page — Freshers’ Data Collection Portal</h3><p>Designed and launched a web application for collecting structured data from incoming college students. Built the frontend with HTML, CSS and JavaScript and implemented PHP backend processing with MySQL storage, validation and a smooth submission flow.</p><div className="tags"><span>HTML</span><span>CSS</span><span>JavaScript</span><span>PHP</span><span>MySQL</span></div></article></div></section>
 <section id="leadership" className="section"><p className="eyebrow">05 / LEADERSHIP</p><h2>Leadership & responsibility</h2><div className="cert-list"><div><b>Senior Body Member — Association of Computer Engineers (ACE)</b><span>June 2025 — Present · Leading and mentoring junior members, organizing technical events and workshops, and coordinating strategic planning.</span></div><div><b>Executive Body Member — ACE</b><span>June 2024 — March 2025 · Co-organized 4+ tech events and coding workshops for 200+ students and coordinated logistics with a 24-member team.</span></div></div></section>
 <section id="contact" className="section contact"><div><p className="eyebrow">06 / CONTACT</p><h2>Have a project or opportunity?</h2><p>I'm open to opportunities where I can apply Java, problem solving and full-stack development skills.</p><div className="contact-info"><span>✉ <a href="mailto:kabishay1@gmail.com">kabishay1@gmail.com</a></span><span>☎ <a href="tel:+918309617699">+91 8309617699</a></span><span>📍 Andhra Pradesh, India</span></div></div><form onSubmit={submit}><div className="row"><label>Name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label>Email<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/></label></div><label>Subject<input value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})} required/></label><label>Message<textarea rows="5" value={form.message} onChange={e=>setForm({...form,message:e.target.value})} required/></label><button className="btn primary" type="submit">Send message ↗</button>{status&&<p className="success">{status}</p>}</form></section>
 </main><footer><span>© 2026 Abishay Karlapudi</span><span>Built with React + Express + MongoDB</span></footer></>}
createRoot(document.getElementById('root')).render(<App/>);
