services:
  - type: web
    name: abishay-karlapudi-portfolio-mern
    runtime: docker
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: CLIENT_ORIGIN
        value: https://abishay-karlapudi-portfolio-mern.onrender.com
